#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.


apt-get update
sed -i "40i \\\trewrite /redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo service nginx restart
