#!/usr/bin/env bash

#add a custom Nginx response header. The goal here is to be able to track
#which web server is answering our HTTP requests, to understand and track
#the way a load balancer works.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo sed -i "12i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
