#!/usr/bin/env bash

#add a custom Nginx response header. The goal here is to be able to track
#which web server is answering our HTTP requests, to understand and track
#the way a load balancer works.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'NGINX HTTP'
sudo sed -i "12i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx start
