#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt install -y haproxy
sudo sed -i "$ aENABLED=1" /etc/init.d/haproxy
sudo echo "

frontend load_balancer
    bind *:80
    mode http
    default_backend webserver

backend webserver
    balance roundrobin
    server 3240-web-01 34.139.29.222:80 check
    server 3240-web-02 34.226.196.12:80 check" | sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy restart
