#!/usr/bin/env bash                                                                                                                             
#Test 1                                                                                                                                         
                                                                                                                                                
sudo rm /etc/nginx/sites-enabled/default                                                                                                        
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default                                                                       
sudo service nginx start               
