#!/usr/bin/env bash
#Script that link sites-enabled to sites-available & starts nginx without a running status

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
