#!/usr/bin/env bash
# display content of file /etc/passwd
# only displays the:
# username
# group id
# Shell full path for the user

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd
